--MAX,MIN,AVG FOR EACH DEPT
SELECT DEPT_CODE, MAX(BASIC) AS MAX_BASIC, MIN(BASIC) AS MIN_BASIC, AVG(BASIC) AS AVG_BASIC FROM EMP GROUP BY DEPT_CODE;

--NO OF FEMALE EMPLOYEES IN EACH DEPARTMENT
SELECT DEPT_CODE, COUNT(*) AS NUMBER_OF_FEMALE_EMPLOYEES FROM EMP WHERE SEX='F' GROUP BY DEPT_CODE;

--DEPARTMENT WISE, CITYWISE NUMBER OF EMPLOYEES
SELECT CITY, DEPT_CODE, COUNT(*) AS NUMBER_OF_EMPLOYEES FROM EMP GROUP BY CITY, DEPT_CODE ORDER BY CITY, DEPT_CODE;

SELECT DEPT_CODE, DESIG_CODE, COUNT(*) AS NUMBER_OF_EMPLOYEES FROM EMP WHERE EXTRACT(YEAR FROM JN_DT)=2023 GROUP BY DEPT_CODE, DESIG_CODE ORDER BY COUNT(*);

SELECT DEPT_CODE, SUM(BASIC) AS TOT_BASIC
    FROM EMP
    WHERE SEX = 'M'
GROUP BY DEPT_CODE
HAVING SUM(BASIC) > 50000
ORDER BY SUM(BASIC) DESC;

SELECT E.EMP_NAME, D.DESIG_DESC,BASIC
    FROM EMP E
    INNER JOIN DESIGNATION D
    ON E.DESIG_CODE = D.DESIG_CODE;
    
    
SELECT E.EMP_NAME, DS.DESIG_CODE, DEP.DEPT_CODE, BASIC
    FROM EMP E
    INNER JOIN DESIGNATION DS
    ON E.DESIG_CODE = DS.DESIG_CODE
    INNER JOIN DEPARTMENT DEP
    ON E.DEPT_CODE = DEP.DEPT_CODE;

SELECT DEPT_CODE
    FROM DEPARTMENT
    WHERE DEPT_CODE NOT IN 
    (SELECT DEPT_CODE FROM EMP);

SELECT D.DEPT_NAME
    FROM DEPARTMENT D
    INNER JOIN EMP E
    ON D.DEPT_CODE = E.DEPT_CODE
    GROUP BY D.DEPT_NAME;
    
SELECT D.DEPT_NAME, COUNT(*)
    FROM EMP E
    INNER JOIN DEPARTMENT D
    ON E.DEPT_CODE = D.DEPT_CODE
    GROUP BY D.DEPT_CODE, D.DEPT_NAME
    HAVING COUNT(*) >= 2;
    
SELECT DEPT_CODE
    FROM EMP
    WHERE BASIC=(SELECT MAX(BASIC)FROM EMP);
    
SELECT D.DESIG_DESC, D.DESIG_CODE
    FROM EMP E
    INNER JOIN DESIGNATION D
    ON E.DESIG_CODE=D.DESIG_CODE
    WHERE BASIC=(SELECT MAX(BASIC)FROM EMP);
    
SELECT DEPT_CODE,COUNT(*)
    FROM EMP
    WHERE DESIG_CODE = 'MANG'
    GROUP BY DEPT_CODE;
    
SELECT BASIC AS MAX_BASIC
FROM (SELECT BASIC
        FROM EMP
        ORDER BY BASIC DESC)
    WHERE ROWNUM=1;

SELECT BASIC AS MIN_BASIC
FROM (SELECT BASIC
        FROM EMP
        ORDER BY BASIC)
    WHERE ROWNUM=1;

/*SELECT A.DEPT_CODE, A.TOTAL_BASIC
    FROM (SELECT DEPT_CODE, SUM(BASIC) AS TOTAL_BASIC
            FROM EMP E GROUP BY DEPT_CODE) A
    WHERE A.TOTAL_BASIC = (SELECT MAX(TOTAL_BASIC) FROM (SELECT DEPT_CODE, SUM(BASIC) AS TOTAL_BASIC
            FROM EMP E GROUP BY DEPT_CODE));
    WHERE NOT EXISTS (SELECT 1 
                        FROM (SELECT DEPT_CODE, SUM(BASIC) AS TOTAL_BASIC
                                FROM EMP E GROUP BY DEPT_CODE) B 
                        WHERE A.TOTAL_BASIC < B.TOTAL_BASIC)*/

SELECT D.DEPT_NAME
    FROM(SELECT DEPT_CODE, SUM(BASIC) AS TOTAL_BASIC
        FROM EMP
        GROUP BY DEPT_CODE
        ORDER BY SUM(BASIC) DESC
        FETCH FIRST 1 ROW ONLY) A
    INNER JOIN DEPARTMENT D
    ON D.DEPT_CODE=A.DEPT_CODE;

SELECT D.DEPT_NAME
    FROM(SELECT DEPT_CODE, AVG(BASIC) AS AVERAGE_BASIC
        FROM EMP
        GROUP BY DEPT_CODE
        ORDER BY AVG(BASIC) DESC
        FETCH FIRST 1 ROW ONLY) A
    INNER JOIN DEPARTMENT D
    ON D.DEPT_CODE=A.DEPT_CODE;
    
SELECT D.DEPT_NAME
    FROM(SELECT DEPT_CODE, COUNT(*) AS MAX_NO_EMP
        FROM EMP
        GROUP BY DEPT_CODE
        ORDER BY COUNT(*) DESC
        FETCH FIRST 1 ROW ONLY) A
    INNER JOIN DEPARTMENT D
    ON D.DEPT_CODE=A.DEPT_CODE;

INSERT INTO EMP VALUES('E11','Srija Kanjilal','1002','ENG','F','Newtown','Kolkata','West Bengal','700091','1000000','24-07-2023');
INSERT INTO EMP VALUES('E12','Ritam Pradhan','1003','CON','M','Newtown','Kolkata','West Bengal','700091','1000000','24-07-2023');
COMMIT;

DELETE FROM EMP
    WHERE DESIG_CODE NOT IN(
    SELECT DESIG_CODE FROM DESIGNATION);
COMMIT;

SELECT EMP_NAME
FROM EMP E1
WHERE SEX = 'F' AND BASIC > (
    SELECT AVG(BASIC)
    FROM EMP E2
    WHERE E2.DEPT_CODE = E1.DEPT_CODE);
    
SELECT COUNT(*)
    FROM EMP
    WHERE SEX='F' AND DESIG_CODE = 'MANAG';
        


    