DROP TABLE A3_EMP_LEAVE_REGISTER;
DROP TABLE A3_LEAVE_TYPE_MASTER;
DROP TABLE A3_EMPLOYEE;
DROP TABLE A3_GRADE_MASTER;
DROP TABLE A3_DEPARTMENT;

CREATE TABLE A3_DEPARTMENT (
  DEPT_CD INT NOT NULL,
  DEPT_NAME   VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_CD)
);

CREATE TABLE A3_GRADE_MASTER (
    GRADE_CD CHAR(1) NOT NULL,
    CONSTRAINT PK_GRADE PRIMARY KEY (GRADE_CD),
    CONSTRAINT CHK_GRADE_CD CHECK (GRADE_CD IN ('A', 'B', 'C'))
);

CREATE TABLE A3_EMPLOYEE (
  EMP_CD INT NOT NULL,
  DEPT_CD INT NOT NULL,
  GRADE_CD CHAR(1) NOT NULL,
  EMP_NAME VARCHAR2(100) NOT NULL,
  EMP_ADDRESS VARCHAR2(100) NOT NULL,
  EMP_CITY VARCHAR2(50) NULL,
  BASIC_SAL INT NOT NULL,
  DATE_OF_JOIN DATE DEFAULT SYSDATE,
  CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMP_CD),
  CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_CD) REFERENCES A3_DEPARTMENT(DEPT_CD),
  CONSTRAINT FK_EMP_GRADE FOREIGN KEY (GRADE_CD) REFERENCES A3_GRADE_MASTER(GRADE_CD),
  CONSTRAINT CHK_EMP_NAME CHECK (UPPER(EMP_NAME) = EMP_NAME),
  CONSTRAINT CHK_EMP_BASIC CHECK (BASIC_SAL BETWEEN 5000 AND 9000)
);

CREATE TABLE A3_LEAVE_TYPE_MASTER (
  LEAVE_TYPE_ID INT NOT NULL,
  LEAVE_DESC VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_LEAVE_TYPE PRIMARY KEY (LEAVE_TYPE_ID)
);

CREATE TABLE A3_EMP_LEAVE_REGISTER (
  EMP_CD INT NOT NULL,
  LEAVE_FROM_DATE DATE NOT NULL,
  LEAVE_TO_DATE DATE NOT NULL,
  LEAVE_TYPE_ID INT NOT NULL,
  CONSTRAINT PK_EMP_LEAVE_REGISTER PRIMARY KEY (EMP_CD, LEAVE_FROM_DATE),
  CONSTRAINT UK_EMP_LEAVE_REGISTER UNIQUE (EMP_CD, LEAVE_TO_DATE),
  CONSTRAINT CHK_LEAVE_FROM_TO CHECK (LEAVE_FROM_DATE <= LEAVE_TO_DATE),
  CONSTRAINT FK_EMP_LEAVE_REG_EMP FOREIGN KEY (EMP_CD) REFERENCES A3_EMPLOYEE(EMP_CD) ON DELETE CASCADE,
  CONSTRAINT FK_EMP_LEAVE_REG_LEAVE_TYPE FOREIGN KEY (LEAVE_TYPE_ID) REFERENCES A3_LEAVE_TYPE_MASTER(LEAVE_TYPE_ID)
);
